// ponytail: Comprehensive OEM parameter catalog for Kelly KLS controllers (KLS7230S & series).
// Maps all 98 parameter items from official manual, Motor ETS software, and kls_registers.json.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum OemCategory {
    Vehicle,
    Motor,
    Control,
    Features,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub enum ValueType {
    U8,
    U16,
    Bool,
    ReadOnlyText,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ParamDef {
    pub addr: u8,
    pub key: &'static str,
    pub label: &'static str,
    pub description: &'static str,
    pub category: OemCategory,
    pub val_type: ValueType,
    pub is_read_only: bool,
    pub is_critical: bool,
    pub min_val: u16,
    pub max_val: u16,
    pub default_val: u16,
    pub unit: &'static str,
}

#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ParamProfile {
    pub vehicle_name: String,
    pub values: std::collections::BTreeMap<u8, u16>,
    pub text_values: std::collections::BTreeMap<u8, String>,
}

pub fn get_all_param_defs() -> &'static [ParamDef] {
    &PARAM_DEFS
}

pub static PARAM_DEFS: [ParamDef; 98] = [
    ParamDef { addr: 0x00, key: "module_name", label: "Module Name", description: "Controller hardware model designation (e.g. KLS7230S). Read-only factory identifier.", category: OemCategory::Vehicle, val_type: ValueType::ReadOnlyText, is_read_only: true, is_critical: false, min_val: 0, max_val: 0, default_val: 0, unit: "" },
    ParamDef { addr: 0x08, key: "user_name", label: "User Name", description: "Custom factory customer variant code / firmware identifier.", category: OemCategory::Vehicle, val_type: ValueType::ReadOnlyText, is_read_only: true, is_critical: false, min_val: 0, max_val: 0, default_val: 0, unit: "" },
    ParamDef { addr: 0x0C, key: "serial_number", label: "Serial Number", description: "Unique factory hardware serial number.", category: OemCategory::Vehicle, val_type: ValueType::ReadOnlyText, is_read_only: true, is_critical: false, min_val: 0, max_val: 0, default_val: 0, unit: "" },
    ParamDef { addr: 0x10, key: "sw_version", label: "Software Version", description: "Controller firmware version number.", category: OemCategory::Vehicle, val_type: ValueType::ReadOnlyText, is_read_only: true, is_critical: false, min_val: 0, max_val: 0, default_val: 0, unit: "" },
    ParamDef { addr: 0x17, key: "ctrl_volt", label: "Controller Volt", description: "Nominal battery pack voltage rating (e.g. 72V). Read-only hardware specification.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: true, is_critical: false, min_val: 0, max_val: 144, default_val: 72, unit: "V" },
    ParamDef { addr: 0x1D, key: "hall_galv", label: "Hall", description: "Internal Hall galvanometer current sensor scale rating in Amperes.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: true, is_critical: false, min_val: 0, max_val: 1000, default_val: 525, unit: "A" },
    ParamDef { addr: 0x1F, key: "phase_curr_max_ad", label: "PhaseCurr Max AD", description: "Maximum ADC raw sampling value corresponding to peak phase current.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: true, is_critical: false, min_val: 409, max_val: 2048, default_val: 380, unit: "AD" },
    ParamDef { addr: 0x84, key: "brake_sw_level", label: "Brake_SW_Level", description: "Active hardware level configuration for brake switch inputs.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 255, default_val: 0, unit: "" },
    ParamDef { addr: 0x99, key: "j_can_address", label: "J CAN Address", description: "J1939 CAN bus node device address (0-255). Default is 127 (or 5 for standard CAN nodes).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 255, default_val: 127, unit: "" },
    ParamDef { addr: 0x19, key: "low_volt", label: "Low Volt", description: "Minimum battery voltage cut-off (V). If battery voltage drops below this threshold for 5s, power cutback occurs to protect cells from over-discharge.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: false, is_critical: true, min_val: 18, max_val: 180, default_val: 18, unit: "V" },
    ParamDef { addr: 0x1B, key: "over_volt", label: "Over Volt", description: "Maximum battery voltage limit (V). Controller shuts down motor drive and disables regen if battery voltage exceeds this threshold to prevent over-charging or MOSFET failure.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: false, is_critical: true, min_val: 18, max_val: 180, default_val: 90, unit: "V" },
    ParamDef { addr: 0x25, key: "curr_percent", label: "Motor_Current%", description: "Maximum motor phase current limit as a percentage (20-100%) of controller peak current. Directly scales peak acceleration torque.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: true, min_val: 20, max_val: 100, default_val: 100, unit: "%" },
    ParamDef { addr: 0x26, key: "battry_limit", label: "Battery_Current%", description: "Maximum battery current limit as a percentage (20-100%) of maximum battery current. Protects battery BMS and limits total DC power draw from battery.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: true, min_val: 20, max_val: 100, default_val: 50, unit: "%" },
    ParamDef { addr: 0x38, key: "id_angle", label: "Identify Angle", description: "Motor auto-identification command status. Set to 170 to initiate self-identification on next power cycle (motor spins automatically to measure Hall angles). Automatically resets to 85 when complete.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: true, min_val: 85, max_val: 170, default_val: 85, unit: "deg" },
    ParamDef { addr: 0x5C, key: "tps_low_err", label: "TPS Low Err", description: "Throttle lower error threshold (0-20%). Triggers TPS error code if throttle voltage falls below this percentage (20% = 1.0V).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 20, default_val: 0, unit: "%" },
    ParamDef { addr: 0x5D, key: "tps_high_err", label: "TPS High Err", description: "Throttle upper error threshold (80-100%). Triggers TPS error code if throttle voltage exceeds this percentage (95% = 4.75V) to detect shorted signals.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 80, max_val: 100, default_val: 95, unit: "%" },
    ParamDef { addr: 0x5F, key: "tps_type", label: "TPS Type", description: "Throttle sensor type selection. 1: 0-5K 3-wire potentiometer pedal; 2: 0-5V Hall active pedal/twist-grip.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 1, max_val: 2, default_val: 1, unit: "" },
    ParamDef { addr: 0x60, key: "tps_dead_low", label: "TPS Dead Low", description: "Throttle start deadzone lower limit (0-60%). Throttle output stays at 0% until pedal is pressed past this percentage (20% = 1.0V).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 60, default_val: 20, unit: "%" },
    ParamDef { addr: 0x61, key: "tps_dead_high", label: "TPS Dead High", description: "Throttle full-power deadzone upper limit (60-95%). Throttle reaches 100% full output when pedal reaches this percentage (80% = 4.0V).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 60, max_val: 95, default_val: 80, unit: "%" },
    ParamDef { addr: 0x62, key: "tps_fwd_map", label: "TPS Fwd MAP", description: "Forward throttle response curve midpoint (0-100%). Adjusts throttle sensitivity curve shape at 50% pedal position (higher value = punchier initial response).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 30, unit: "%" },
    ParamDef { addr: 0x63, key: "tps_rev_map", label: "TPS Rev MAP", description: "Reverse throttle response curve midpoint (0-100%). Adjusts reverse throttle curve shape at 50% pedal position.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 20, unit: "%" },
    ParamDef { addr: 0x64, key: "brake_type", label: "Brake Type", description: "Regenerative braking input mode. 0: Switch regen (digital switch input); 1: 0-5K resistance pedal analog regen; 2: 0-5V active Hall pedal analog regen.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 2, default_val: 0, unit: "" },
    ParamDef { addr: 0x65, key: "brake_dead_low", label: "Brake Dead Low", description: "Analog brake pedal lower deadzone limit (5-40%). Regen braking starts when pedal exceeds this percentage (20% = 1.0V).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 5, max_val: 40, default_val: 20, unit: "%" },
    ParamDef { addr: 0x66, key: "brake_dead_high", label: "Brake Dead High", description: "Analog brake pedal upper deadzone limit (60-95%). Maximum regen torque is reached when pedal reaches this percentage (80% = 4.0V).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 60, max_val: 95, default_val: 80, unit: "%" },
    ParamDef { addr: 0x69, key: "max_output_fre", label: "Max Output Fre", description: "Maximum electrical fundamental output frequency (50-1200 Hz). Limits maximum achievable motor electrical frequency.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 50, max_val: 1200, default_val: 1000, unit: "Hz" },
    ParamDef { addr: 0x6B, key: "max_speed", label: "Max Speed", description: "Motor maximum mechanical speed limit in RPM (0-16000 RPM). Limits top vehicle speed.", category: OemCategory::Vehicle, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 16000, default_val: 4000, unit: "RPM" },
    ParamDef { addr: 0x6D, key: "max_fwd_speed_pct", label: "Max Fwd Speed %", description: "Maximum forward speed limit as a percentage (0-100%) of Motor Max Speed.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 100, unit: "%" },
    ParamDef { addr: 0x6E, key: "max_rev_speed_pct", label: "Max Rev Speed %", description: "Maximum reverse speed limit as a percentage (0-100%) of Motor Max Speed.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 100, unit: "%" },
    ParamDef { addr: 0x70, key: "midspeed_forw", label: "MidSpeed Forw", description: "Maximum forward speed in middle speed gear (0-100%) when 3-speed switch is enabled.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 50, unit: "%" },
    ParamDef { addr: 0x71, key: "midspeed_rev", label: "MidSpeed Rev", description: "Maximum reverse speed in middle speed gear (0-100%) when 3-speed switch is enabled.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 30, unit: "%" },
    ParamDef { addr: 0x72, key: "lowspeed_forw", label: "LowSpeed Forw", description: "Maximum forward speed in low speed gear (0-100%) when 3-speed switch is enabled.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 50, unit: "%" },
    ParamDef { addr: 0x73, key: "lowspeed_rev", label: "LowSpeed Rev", description: "Maximum reverse speed in low speed gear (0-100%) when 3-speed switch is enabled.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 30, unit: "%" },
    ParamDef { addr: 0x74, key: "three_speed", label: "Three Speed", description: "Number of gear speed modes enabled. 0: 1-speed (max speed mode only); 1: 2-speed mode (mid & max); 2: 3-speed mode (low, mid, max).", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 2, default_val: 0, unit: "" },
    ParamDef { addr: 0x75, key: "pwm_frequency", label: "PWM frequency", description: "SVPWM carrier modulation frequency (10, 16, or 20 kHz). 20 kHz provides silent motor operation; lower frequencies reduce MOSFET switching heat.", category: OemCategory::Vehicle, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 10, max_val: 20, default_val: 16, unit: "kHz" },
    ParamDef { addr: 0x80, key: "iq_kp", label: "IQ Kp", description: "Proportional gain (Kp) for Q-axis (torque) current loop at low speed (<400 RPM). Higher values speed up torque response but may cause startup vibration.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 1500, unit: "" },
    ParamDef { addr: 0x82, key: "iq_ki", label: "IQ Ki", description: "Integral gain (Ki) for Q-axis (torque) current loop at low speed (<400 RPM). Improves steady-state current accuracy.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 30, unit: "" },
    ParamDef { addr: 0x86, key: "id_kp", label: "ID Kp", description: "Proportional gain (Kp) for D-axis (flux) current loop at low speed (<400 RPM). Controls field weakening and d-axis current response.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 1500, unit: "" },
    ParamDef { addr: 0x88, key: "id_ki", label: "ID Ki", description: "Integral gain (Ki) for D-axis (flux) current loop at low speed (<400 RPM). Enhances flux control stability.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 30, unit: "" },
    ParamDef { addr: 0x96, key: "ms_acqr_kp", label: "MS_ACQR_Kp", description: "Proportional gain (Kp) for Q-axis current loop at medium/high speed (>400 RPM). Accelerates high-speed acceleration response.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 1500, unit: "" },
    ParamDef { addr: 0x98, key: "ms_acqr_ki", label: "MS_ACQR_Ki", description: "Integral gain (Ki) for Q-axis current loop at medium/high speed (>400 RPM). Maintains torque precision at higher RPM.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 30, unit: "" },
    ParamDef { addr: 0x9A, key: "ms_acdr_kp", label: "MS_ACDR_Kp", description: "Proportional gain (Kp) for D-axis current loop at medium/high speed (>400 RPM). Optimizes high-speed field weakening response.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 1500, unit: "" },
    ParamDef { addr: 0x9C, key: "ms_acdr_ki", label: "MS_ACDR_Ki", description: "Integral gain (Ki) for D-axis current loop at medium/high speed (>400 RPM). Ensures stability during high-speed field weakening.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 32767, default_val: 30, unit: "" },
    ParamDef { addr: 0x9D, key: "brk_ad_brk_pct", label: "BRK_AD Brk %", description: "Analog brake pedal regen strength (0-50%). Sets maximum braking torque percentage when using analog brake pedal regen.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 50, default_val: 0, unit: "%" },
    ParamDef { addr: 0x9E, key: "anti_theft_pct", label: "Anti-theft %", description: "Anti-theft locking torque strength (0-30%). Percentage of maximum current used to lock motor rotor when alarm is triggered.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 30, default_val: 15, unit: "%" },
    ParamDef { addr: 0x9F, key: "brk_speed_limit", label: "Brk_Speed Limit", description: "Minimum motor speed threshold (0-500 RPM) to activate regen braking. Regen automatically disengages below this RPM.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 500, default_val: 0, unit: "RPM" },
    ParamDef { addr: 0xA0, key: "rls_tps_brk_pct", label: "RLS_TPS Brk %", description: "Throttle release (off-throttle / overrun) regen braking strength (0-50%). Provides engine-braking effect when releasing throttle.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 50, default_val: 0, unit: "%" },
    ParamDef { addr: 0xA1, key: "ntl_brk_pct", label: "NTL Brk %", description: "Neutral gear regen braking strength (0-50%). Sets braking torque percentage when vehicle is rolling in neutral.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 50, default_val: 0, unit: "%" },
    ParamDef { addr: 0xA2, key: "accel_time", label: "Accel Time", description: "Drive torque ramp-up time (1-250 = 0.1s to 25.0s). Time taken for torque to rise from 0 to maximum. Lower value = faster throttle acceleration.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 1, max_val: 250, default_val: 5, unit: "x0.1s" },
    ParamDef { addr: 0xA3, key: "accel_rls_time", label: "Accel Rls Time", description: "Drive torque release delay time (1-250 = 0.1s to 25.0s). Time taken for drive torque to ramp down from maximum to 0 upon releasing throttle.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 1, max_val: 250, default_val: 1, unit: "x0.1s" },
    ParamDef { addr: 0xA4, key: "brake_time", label: "Brake Time", description: "Braking torque ramp-up time (1-250 = 0.1s to 25.0s). Time taken for regen braking torque to ramp up from 0 to maximum. Provides smooth braking onset.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 1, max_val: 250, default_val: 5, unit: "x0.1s" },
    ParamDef { addr: 0xA5, key: "brake_rls_time", label: "Brake Rls Time", description: "Braking torque release delay time (1-250 = 0.1s to 25.0s). Time taken for regen braking torque to decay from maximum to 0.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 1, max_val: 250, default_val: 1, unit: "x0.1s" },
    ParamDef { addr: 0xA6, key: "brk_sw_brk_pct", label: "BRK_SW Brk %", description: "Digital brake switch regen braking strength (0-50%). Braking torque percentage when brake switch input is activated.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 50, default_val: 10, unit: "%" },
    ParamDef { addr: 0xA7, key: "change_dir_brk_pct", label: "Change Dir Brk%", description: "Direction change (plugging) regen braking strength (0-50%). Braking torque applied when switching FWD/REV while moving.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 50, default_val: 5, unit: "%" },
    ParamDef { addr: 0xA8, key: "compensation", label: "Compensation", description: "Hill-hold / anti-slip compensation torque percentage (0-100%). Provides hold torque to prevent rolling backward on inclines.", category: OemCategory::Control, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 20, unit: "%" },
    ParamDef { addr: 0xA9, key: "ivt_brk_max", label: "IVT BRK Max", description: "Maximum motor RPM limit (0-10000 RPM) allowing direction change plugging regen braking.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 10000, default_val: 10000, unit: "RPM" },
    ParamDef { addr: 0xAA, key: "ivt_brk_min", label: "IVT BRK Min", description: "Minimum motor RPM limit (0-5000 RPM) required to engage direction change plugging regen braking.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 5000, default_val: 50, unit: "RPM" },
    ParamDef { addr: 0xFA, key: "torque_speed_kp", label: "Torque Speed Kp", description: "Proportional gain (Kp) for Q-axis loop in Torque Mode at low speed (<400 RPM). Tunes startup responsiveness.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 10000, default_val: 3000, unit: "" },
    ParamDef { addr: 0xFC, key: "torque_speed_ki", label: "Torque Speed Ki", description: "Integral gain (Ki) for Q-axis loop in Torque Mode at low speed (<400 RPM). Tunes steady-state torque accuracy.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 500, default_val: 80, unit: "" },
    ParamDef { addr: 0xFE, key: "speed_err_limit", label: "Speed Err Limit", description: "Speed loop error signal limit (50-4000) for torque mode control loops.", category: OemCategory::Control, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 50, max_val: 4000, default_val: 1000, unit: "" },
    ParamDef { addr: 0x20, key: "motor_nom_curr", label: "Motor Nominal", description: "Motor nominal current setting during auto-identification (0-1000 A). Set to match motor rated current for proper parameter identification.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: false, is_critical: true, min_val: 0, max_val: 1000, default_val: 80, unit: "A" },
    ParamDef { addr: 0x40, key: "motor_poles", label: "Motor Poles", description: "Number of motor magnetic poles (2-128 = 2x pole pairs). Crucial for accurate RPM calculation and electrical commutation.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: true, min_val: 2, max_val: 128, default_val: 8, unit: "" },
    ParamDef { addr: 0x41, key: "speed_sensor_type", label: "Speed Sensor", description: "Primary motor position sensor type. 2: 3-phase Hall effect sensors; 3: Magnetic encoder / resolver.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 2, max_val: 3, default_val: 2, unit: "" },
    ParamDef { addr: 0x42, key: "resolver_poles", label: "Resolver Poles", description: "Number of poles for resolver sensor (2-32). Reserved for resolver equipped motors.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 2, max_val: 32, default_val: 2, unit: "" },
    ParamDef { addr: 0x43, key: "min_excitation", label: "Min Excitation", description: "Minimum excitation current coefficient (0-100 A) for field weakening. If 0, field weakening speed boost is inactive.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 0, unit: "" },
    ParamDef { addr: 0x44, key: "motor_temp_sensor", label: "Motor Temp", description: "Motor temperature thermistor type. 0: Disabled / None; 1: KTY84-130 / KTY84-150; 2: KTY83-122.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 2, default_val: 0, unit: "" },
    ParamDef { addr: 0x46, key: "high_temp_cutoff", label: "High Temp Cut ℃", description: "Motor over-temperature shutdown threshold (60-170 °C). Controller stops driving if motor temperature exceeds this value.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 60, max_val: 170, default_val: 130, unit: "°C" },
    ParamDef { addr: 0x47, key: "high_temp_striae", label: "High Temp Str℃", description: "Motor high-temperature current foldback start threshold (0-170 °C). Drive current begins ramping down above this temp.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 170, default_val: 100, unit: "°C" },
    ParamDef { addr: 0x48, key: "high_temp_week_pct", label: "High Temp Week %", description: "Motor high-temperature foldback strength percentage (0-100%). Defines current reduction percentage between start and cutoff temp.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 0, max_val: 100, default_val: 0, unit: "%" },
    ParamDef { addr: 0x49, key: "resume_off", label: "Resume ℃", description: "Motor over-temperature recovery threshold (60-170 °C). Controller resumes operation once motor cools down to this temp.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: false, is_critical: false, min_val: 60, max_val: 170, default_val: 110, unit: "°C" },
    ParamDef { addr: 0x4D, key: "line_hall_zero", label: "Line Hall Zero", description: "Sine/Cosine sensor zero-point voltage calibration value (1-1023). Formula: Zero V = Value / 1024 * 5V.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 1, max_val: 1023, default_val: 508, unit: "" },
    ParamDef { addr: 0x4E, key: "line_hall_amp", label: "Line Hall", description: "Sine/Cosine sensor signal amplitude calibration value (1-1024). Valid range 153.6 to 256 for normal signal voltage.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 1, max_val: 1024, default_val: 410, unit: "" },
    ParamDef { addr: 0x4F, key: "line_hall_high_err", label: "Line Hall High", description: "Sine/Cosine sensor high-amplitude error threshold limit (1-1023). Triggers angle sensor fault if amplitude exceeds this.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 1, max_val: 1023, default_val: 972, unit: "" },
    ParamDef { addr: 0x50, key: "line_hall_low_err", label: "Line Hall Low", description: "Sine/Cosine sensor low-amplitude error threshold limit (1-1023). Triggers angle sensor fault if amplitude drops below this.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: false, is_critical: false, min_val: 1, max_val: 1023, default_val: 50, unit: "" },
    ParamDef { addr: 0x51, key: "swap_motor_phase", label: "Swap Motor Phase", description: "Motor phase swapping status flag for sine/cosine sensor alignment. 0: Disabled; 1: Enabled; 255: Identification error.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 255, default_val: 0, unit: "" },
    ParamDef { addr: 0x52, key: "resolver_init_angle", label: "Resolver init", description: "Synchro initial angle reference point (0-65535) for sine/cosine or magnetic encoder position alignment.", category: OemCategory::Motor, val_type: ValueType::U16, is_read_only: true, is_critical: false, min_val: 0, max_val: 65535, default_val: 8129, unit: "deg" },
    ParamDef { addr: 0x06, key: "hall_0deg", label: "0° Hall value", description: "Hall sensor sequence value at 0° electrical angle. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 2, unit: "" },
    ParamDef { addr: 0x07, key: "hall_60deg", label: "60° Hall value", description: "Hall sensor sequence value at 60° electrical angle. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 6, unit: "" },
    ParamDef { addr: 0x0A, key: "hall_120deg", label: "120° Hall value", description: "Hall sensor sequence value at 120° electrical angle. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 4, unit: "" },
    ParamDef { addr: 0x0B, key: "hall_180deg", label: "180° Hall value", description: "Hall sensor sequence value at 180° electrical angle. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 5, unit: "" },
    ParamDef { addr: 0x0E, key: "hall_240deg", label: "240° Hall value", description: "Hall sensor sequence value at 240° electrical angle. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 1, unit: "" },
    ParamDef { addr: 0x0F, key: "hall_300deg", label: "300° Hall value", description: "Hall sensor sequence value at 300° electrical angle. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 3, unit: "" },
    ParamDef { addr: 0x53, key: "fwd_ha_rising", label: "Forward HA (Rising)", description: "Forward direction Hall-A rising edge sequence value. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 6, unit: "" },
    ParamDef { addr: 0x54, key: "fwd_ha_falling", label: "Forward HA (Falling)", description: "Forward direction Hall-A falling edge sequence value. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 1, unit: "" },
    ParamDef { addr: 0x55, key: "rev_ha_rising", label: "Reverse HA (Rising)", description: "Reverse direction Hall-A rising edge sequence value. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 5, unit: "" },
    ParamDef { addr: 0x57, key: "rev_ha_falling", label: "Reverse HA (Falling)", description: "Reverse direction Hall-A falling edge sequence value. Auto-generated during self-identification.", category: OemCategory::Motor, val_type: ValueType::U8, is_read_only: true, is_critical: false, min_val: 0, max_val: 7, default_val: 2, unit: "" },
    ParamDef { addr: 0x14, key: "startup_h_pedal", label: "Startup H-Pedal", description: "High-Pedal Protection on Startup (HPD). When enabled, prevents accidental runaway if throttle is pressed when powering on controller.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 1, unit: "" },
    ParamDef { addr: 0x21, key: "brake_h_pedal", label: "Brake H-Pedal", description: "Brake High-Pedal Protection. When enabled, reports a high-pedal fault and cuts motor output if throttle and brake are pressed simultaneously.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x22, key: "ntl_h_pedal", label: "NTL H-Pedal", description: "Neutral High-Pedal Protection. When enabled, prevents accidental starting if throttle is pressed while shifting gears out of neutral.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x23, key: "joystick", label: "Joystick", description: "Joystick Throttle Mode. Enables bi-directional 0-5V joystick (0-2.5V = Reverse, 2.5V = Neutral, 2.5V-5V = Forward).", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x24, key: "three_gears_switch", label: "Three Gears Switch", description: "Three-Gear Operating Switch. Enabled: FWD / Neutral / REV 3-position gear selection; Disabled: Forward only.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x27, key: "boost", label: "Boost", description: "Boost Switch Mode. Enabled: Connecting Pin 2 (Brake_AN) to 12V triggers full boost power regardless of throttle position; Disabled: Pin 2 operates variable regen.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x28, key: "foot_switch", label: "Foot Switch", description: "Throttle Enable Microswitch (Foot_SW). Enabled: Pin 15 must be connected to 12V for throttle output to be active.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x29, key: "sw_level", label: "SW Level", description: "Digital Switch Input Voltage Level Logic. Enabled (Checked): High active (12V = ON); Disabled (Unchecked): Low active (0V / GND = ON).", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 1, unit: "" },
    ParamDef { addr: 0x2A, key: "controller_type_kim", label: "0,KIM;1,KIM", description: "Controller internal variant selection bit. Checked: KIM model family logic; Unchecked: HIM model family logic.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 1, unit: "" },
    ParamDef { addr: 0x2B, key: "cruise", label: "Cruise", description: "Cruise Control Function. Enabled: Holding steady throttle for >3s enters cruise mode. Automatically disengages if eRPM drops below 4000 or brake is hit.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x2C, key: "anti_theft_en", label: "Anti-theft", description: "Anti-Theft Alarm Lock Function. Enabled: Controller resists motor rotation and applies counter-torque when external anti-theft alarm is triggered.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x2D, key: "anti_slip", label: "Anti-Slip", description: "Bidirectional Anti-Slip Hill Hold. Enabled: Controller detects backward rollback from standstill and applies braking/hold torque to prevent vehicle from slipping.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
    ParamDef { addr: 0x2E, key: "change_direction", label: "Change Direction", description: "Motor Rotation Direction Swap. Enabled: Reverses motor direction after auto-identification without swapping physical motor phase wires.", category: OemCategory::Features, val_type: ValueType::Bool, is_read_only: false, is_critical: false, min_val: 0, max_val: 1, default_val: 0, unit: "" },
];

pub fn export_profile_to_json(profile: &ParamProfile) -> Result<String, String> {
    serde_json::to_string_pretty(profile).map_err(|e| e.to_string())
}

pub fn import_profile_from_json(json_str: &str) -> Result<ParamProfile, String> {
    serde_json::from_str(json_str).map_err(|e| e.to_string())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_param_defs_count() {
        assert_eq!(PARAM_DEFS.len(), 98);
        assert_eq!(get_all_param_defs().len(), 98);
    }

    #[test]
    fn test_profile_json_roundtrip() {
        let mut profile = ParamProfile {
            vehicle_name: "KLS7230S-Test".to_string(),
            values: std::collections::BTreeMap::new(),
            text_values: std::collections::BTreeMap::new(),
        };
        for def in get_all_param_defs() {
            profile.values.insert(def.addr, def.default_val);
        }

        let json = export_profile_to_json(&profile).unwrap();
        let imported = import_profile_from_json(&json).unwrap();

        assert_eq!(imported.vehicle_name, "KLS7230S-Test");
        assert_eq!(imported.values.len(), 98);
        assert_eq!(imported.values.get(&0x17), Some(&72));
    }
}
