name: Reusable Test

on:
  workflow_call:

jobs:
  test:
    name: Test & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libudev-dev libgtk-3-dev pkg-config

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          components: clippy, rustfmt

      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Check code formatting
        run: cargo fmt --check

      - name: Run clippy lints
        run: cargo clippy -- -D warnings

      - name: Run tests
        run: cargo test --all-targets
