name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  test:
    uses: ./.github/workflows/_test.yml

  build:
    needs: test
    uses: ./.github/workflows/_build.yml

  release:
    needs: build
    uses: ./.github/workflows/_release.yml
